---
- name: Set swappiness to 0
  sysctl:
    name: vm.swappiness
    value: '0'
    state: present

- name: Disable THP permanently
  lineinfile: 
    dest: /etc/rc.local
    line: "for i in /sys/kernel/mm/*transparent_hugepage/enabled; do echo never > $i; done"

- name: Disable THP-defrag permanently
  lineinfile:
    dest: /etc/rc.local
    line: "for i in /sys/kernel/mm/*transparent_hugepage/defrag; do echo never > $i; done"

- name: Disable current THP
  shell: for i in /sys/kernel/mm/*transparent_hugepage/enabled; do echo never > $i; done

- name: Disable current THP defrag
  shell: for i in /sys/kernel/mm/*transparent_hugepage/defrag; do echo never > $i; done
